backend:
  name: git-gateway
  publish_mode: editorial_workflow
  branch: master # Branch to update (optional; defaults to master)

media_folder: "themes/ync/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "site/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Subtitle, name: subtitle, widget: string}
      - {label: Image, name: image, widget: image}
      - {label: "Blurb", name: blurb, widget: object, fields: [
      {label: "Heading", name: "heading", widget: string},
      {label: "Text", name: "text", widget: "text"}]}
      - {label: "Intro", name: intro, widget: object, fields: [
      {label: "Heading", name: "heading", widget: string},
      {label: "Text", name: "text", widget: "text"}]}
      - {label: "Products", name: products, widget: list, fields: [
      {label: "Image", name: "image", widget: "image"},
      {label: "Text", name: "text", widget: "text"}]}
      - {label: "Values", name: "values", widget: "object", fields: [
      {label: "Heading", name: "heading", widget: string},
      {label: "Text", name: "text", widget: "text"}]}
  - name: "home-section"
    label: "Homepage"
    files:
      - file: "data/home/herobanner.json"
        label: "Banner"
        name: "banner"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Image, name: image, widget: image}
      - file: "data/home/projects.json"
        label: "Projects"
        name: "projects"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Image, name: image, widget: image}
  - name: "menu"
      label: "Menu"
      files:
        - file: "data/menu/menu.json"
          label: "Menu"
          name: "menu"
          fields:
            - {label: "Menu", name: menu, widget: list, fields: [
              {label: "Text", name: "text", widget: string},
              {label: "Link", name: "text", widget: string},
              {label: "Custom class", name: "text", widget: string}]}
